# Generated by Django 4.2.13 on 2024-10-07 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("myapp", "0003_user_avatar_user_gender"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPost",
            fields=[
                ("post_id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.TextField()),
                ("description", models.TextField()),
                ("browse_count", models.IntegerField(default=0)),
                ("like_count", models.IntegerField(default=0)),
                ("showImages", models.ManyToManyField(to="myapp.image")),
            ],
        ),
        migrations.CreateModel(
            name="Tags",
            fields=[
                ("tag_id", models.AutoField(primary_key=True, serialize=False)),
                ("tag_name", models.TextField()),
                ("post", models.ManyToManyField(to="community.userpost")),
            ],
        ),
    ]
