# Generated by Django 4.2.19 on 2025-06-01 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpost",
            name="comment_count",
            field=models.IntegerField(default=0),
        ),
    ]
