# Generated by Django 4.2.19 on 2025-06-04 08:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("community", "0003_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpost",
            name="like_users",
            field=models.ManyToManyField(
                related_name="liked_posts", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
