# Generated by Django 4.2.13 on 2024-10-06 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="image",
            old_name="user_id",
            new_name="user",
        ),
        migrations.RemoveField(
            model_name="user",
            name="email",
        ),
    ]
